// src/components/ModelList.tsx
import React, { useMemo } from 'react';
import { useModelStore } from '../store';
import type { Model } from '../utils/types';
import './ModelList.css';

const categoryLabelMap: Record<string, string> = {
  helmet: '头盔',
  character: '人物',
  furniture: '家具',
  car: '汽车',
  data: '数据',
  '压力数据': '压力数据',
  '零件': '零件',
  '机器': '机器',
  '灯': '灯',
  home: '家居',
  remote: '远程模型',
  uploaded: '本地上传'
};

interface ModelListProps {
  search: string;
  category: string;
  onSelect: (model: Model) => void;
}

export default function ModelList({ search, category, onSelect }: ModelListProps) {
  const models = useModelStore((state) => state.models);

  const filteredModels = useMemo(() => {
    return models.filter((m) =>
      (!category || m.category === category) &&
      (!search || m.name.toLowerCase().includes(search.toLowerCase()))
    );
  }, [models, search, category]);

  const getTagClass = (type: string) => {
    switch (type) {
      case 'gltf':
      case 'glb':
        return 'tag-success';
      case 'fbx':
        return 'tag-warning';
      case 'obj':
        return 'tag-info';
      case 'stl':
        return 'tag-primary';
      case 'step':
      case 'iges':
        return 'tag-danger';
      default:
        return 'tag-info';
    }
  };

  const getCategoryTagClass = (cat: string) => {
    switch (cat) {
      case 'helmet': return 'tag-danger';
      case 'character': return 'tag-warning';
      case 'furniture': return 'tag-info';
      case 'data': return 'tag-primary';
      case 'uploaded': return 'tag-success';
      case 'remote': return 'tag-warning';
      case 'home': return 'tag-primary';
      default: return 'tag-info';
    }
  };

  const getCategoryName = (cat: string) => categoryLabelMap[cat] || cat;

  const formatModelName = (name: string) => {
    const [displayName] = name.split('__uploaded_');
    return displayName || name;
  };

  if (filteredModels.length === 0) {
    return <div className="empty-state">没有找到匹配的模型</div>;
  }

  return (
    <div className="model-grid">
      {filteredModels.map((model) => (
        <div key={model.name} className="model-card" onClick={() => onSelect(model)}>
          <div className="model-thumbnail">
            <div
              className="model-thumbnail-image"
              style={{ backgroundImage: `url(${model.thumbnail || '/assets/placeholder.svg'})` }}
            />
          </div>
          <div className="model-info">
            <h3>{formatModelName(model.name)}</h3>
            <div className="tags">
              <span className={`tag ${getTagClass(model.type)}`}>{model.type}</span>
              <span className={`tag ${getCategoryTagClass(model.category)}`}>
                {getCategoryName(model.category)}
              </span>
            </div>
          </div>
        </div>
      ))}
    </div>
  );
}

// src/components/ModelList.vue
<template>
  <div class="model-list">
    <el-empty v-if="filteredModels.length === 0" description="没有找到匹配的模型" />
    
    <el-row :gutter="20">
      <el-col :xs="24" :sm="12" :md="8" :lg="6" v-for="model in filteredModels" :key="model.name">
        <el-card 
          shadow="hover" 
          @click="() => $emit('select', model)" 
          class="model-card"
          :body-style="{ padding: '0px' }"
        >
          <div class="model-thumbnail">
            <div
              class="model-thumbnail-image"
              :style="{ backgroundImage: `url(${model.thumbnail || '/assets/placeholder.svg'})` }"
            ></div>
          </div>
          <div class="model-info">
            <h3>{{ formatModelName(model.name) }}</h3>
            <el-tag size="small" :type="getTagType(model.type)">{{ model.type }}</el-tag>
            <el-tag size="small" :type="getCategoryTagType(model.category)" class="category-tag">
              {{ getCategoryName(model.category) }}
            </el-tag>
          </div>
        </el-card>
      </el-col>
    </el-row>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useModelStore } from '../store'
import type { Model } from '../utils/types'

const categoryLabelMap: Record<string, string> = {
  helmet: '头盔',
  character: '人物',
  furniture: '家具',
  car: '汽车',
  data: '数据',
  '压力数据': '压力数据',
  '零件': '零件',
  '机器': '机器',
  '灯': '灯',
  home: '家居',
  remote: '远程模型',
  uploaded: '本地上传'
}

// 定义组件属性
const props = defineProps<{ 
  search: string, 
  category: string 
}>()

// 定义事件
defineEmits<{
  (e: 'select', model: Model): void
}>()

// 获取模型存储
const store = useModelStore()

// 过滤模型列表
const filteredModels = computed(() => {
  return store.models.filter(m =>
    (!props.category || m.category === props.category) &&
    (!props.search || m.name.toLowerCase().includes(props.search.toLowerCase()))
  )
})

/**
 * 获取模型类型对应的标签类型
 * @param type 模型类型
 * @returns 标签类型（Element Plus 支持的几种类型）
 */
function getTagType(type: string): 'primary' | 'success' | 'warning' | 'info' | 'danger' {
  switch (type) {
    case 'gltf':
    case 'glb':
      return 'success'
    case 'fbx':
      return 'warning'
    case 'obj':
      return 'info'
    case 'stl':
      return 'primary'
    case 'step':
    case 'iges':
      return 'danger'
    default:
      // 其余未知类型统一用 info 显示，避免传入非法值
      return 'info'
  }
}

/**
 * 获取分类对应的标签类型
 * @param category 分类
 * @returns 标签类型（Element Plus 支持的几种类型）
 */
function getCategoryTagType(category: string): 'primary' | 'success' | 'warning' | 'info' | 'danger' {
  switch (category) {
    case 'helmet':
      return 'danger'
    case 'character':
      return 'warning'
    case 'furniture':
      return 'info'
    case 'data':
      return 'primary'
    case 'uploaded':
      return 'success'
    case 'remote':
      return 'warning'
    case 'home':
      return 'primary'
    default:
      // 其他分类统一用 info 展示，避免非法值
      return 'info'
  }
}

/**
 * 获取分类名称
 * @param category 分类代码
 * @returns 分类名称
 */
function getCategoryName(category: string): string {
  return categoryLabelMap[category] || category
}

function formatModelName(name: string): string {
  const [displayName] = name.split('__uploaded_')
  return displayName || name
}
</script>

<style scoped>
.model-list {
  margin-top: 20px;
}

.model-card {
  cursor: pointer;
  transition: transform 0.3s;
  margin-bottom: 20px;
  overflow: hidden;
}

.model-card:hover {
  transform: translateY(-5px);
  box-shadow: 0 10px 20px rgba(0, 0, 0, 0.1);
}

.model-thumbnail {
  height: 150px;
  overflow: hidden;
  background-color: #f5f7fa;
}

.model-thumbnail-image {
  width: 100%;
  height: 100%;
  background-position: center;
  background-repeat: no-repeat;
  background-size: contain;
  transition: transform 0.3s;
}

.model-card:hover .model-thumbnail-image {
  transform: scale(1.05);
}

.model-info {
  padding: 14px;
}

.model-info h3 {
  margin: 0 0 10px 0;
  font-size: 16px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.category-tag {
  margin-left: 5px;
}
</style>
