// src/components/PressureViewer/index.vue
<template>
  <div class="pressure-viewer">
    <div ref="container" class="viewer-container"></div>

    <!-- 控制面板 -->
    <PressureControlPanel
      v-if="!isLoading"
      v-model:colorMap="colorMap"
      v-model:minValue="minValue"
      v-model:maxValue="maxValue"
      :pressure-stats="pressureStats"
      :get-color-for-pressure="getColorForPressure"
      :format-pressure-value="formatPressureValue"
      @color-map-change="updateColorMap"
      @range-change="updateRange"
      @reset="reset"
    />

    <!-- 压力颜色条图例 -->
    <PressureLegend
      v-if="!isLoading"
      :color-bar-gradient="colorBarGradient"
      :pressure-labels="pressureLabels"
      :min-value="minValue"
      :max-value="maxValue"
      :selected-pressure="selectedPressure"
      :get-color-for-pressure="getColorForPressure"
      :format-pressure-value="formatPressureValue"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount } from 'vue'
import * as THREE from 'three'
import { OrbitControls } from 'three/addons/controls/OrbitControls.js'
import { createPressureVisualization, type PressureVisualization } from '../../utils/pressureData'
import { usePressureVisualization } from '../../composables'
import type { Model } from '../../core/types'
import PressureControlPanel from './PressureControlPanel.vue'
import PressureLegend from './PressureLegend.vue'

// Props
const props = defineProps<{
  model: Model
}>()

// Emits
const emit = defineEmits(['loading', 'loaded', 'error'])

// Refs
const container = ref<HTMLDivElement>()
const isLoading = ref(true)

// 使用 composable
const {
  colorMap,
  minValue,
  maxValue,
  selectedPressure,
  pressureStats,
  pressureLabels,
  colorBarGradient,
  getColorForPressure,
  formatPressureValue,
  setPressureStats,
  setSelectedPressure
} = usePressureVisualization()

// Three.js 对象
let scene: THREE.Scene | null = null
let camera: THREE.PerspectiveCamera | null = null
let renderer: THREE.WebGLRenderer | null = null
let controls: OrbitControls | null = null
let pressureViz: PressureVisualization | null = null
let animationId: number

/**
 * 初始化场景
 */
async function init() {
  if (!container.value || !props.model) return

  try {
    // 创建场景
    scene = new THREE.Scene()
    scene.background = new THREE.Color(0xffffff)

    // 创建相机
    const width = container.value.clientWidth
    const height = container.value.clientHeight
    camera = new THREE.PerspectiveCamera(60, width / height, 1, 100)
    camera.position.set(0, 0, 10)

    // 创建渲染器
    renderer = new THREE.WebGLRenderer({ antialias: true })
    renderer.setPixelRatio(window.devicePixelRatio)
    renderer.setSize(width, height)
    container.value.appendChild(renderer.domElement)

    // 创建控制器
    controls = new OrbitControls(camera, renderer.domElement)
    controls.addEventListener('change', render)

    // 添加灯光
    const pointLight = new THREE.PointLight(0xffffff, 3, 0, 0)
    camera.add(pointLight)
    scene.add(camera)

    // 创建压力数据可视化
    pressureViz = await createPressureVisualization(
      scene,
      props.model.file,
      {
        colorMap: colorMap.value,
        minValue: minValue.value,
        maxValue: maxValue.value
      },
      {
        loading: (progress: number) => emit('loading', progress),
        loaded: () => {
          isLoading.value = false
          emit('loaded')
        },
        error: (error: unknown) => {
          isLoading.value = false
          emit('error', error)
        }
      }
    )

    // 添加图例到场景
    scene.add(pressureViz.legend)

    // 计算压力统计
    calculatePressureStats()

    // 处理窗口大小变化
    window.addEventListener('resize', onWindowResize)

    // 添加鼠标交互
    setupMouseInteraction()

    // 开始渲染循环
    animate()
  } catch (e) {
    console.error('压力数据可视化初始化失败:', e)
    isLoading.value = false
    emit('error', e)
  }
}

/**
 * 窗口大小变化处理
 */
function onWindowResize() {
  if (!camera || !renderer || !container.value) return

  const width = container.value.clientWidth
  const height = container.value.clientHeight

  camera.aspect = width / height
  camera.updateProjectionMatrix()
  renderer.setSize(width, height)
  render()
}

/**
 * 渲染函数
 */
function render() {
  if (!renderer || !scene || !camera) return
  renderer.render(scene, camera)
}

/**
 * 动画循环
 */
function animate() {
  animationId = requestAnimationFrame(animate)
  if (controls) controls.update()
  render()
}

/**
 * 更新颜色映射
 */
function updateColorMap() {
  if (pressureViz) {
    pressureViz.updateColorMap(colorMap.value)
    render()
  }
}

/**
 * 更新数值范围
 */
function updateRange() {
  if (pressureViz) {
    pressureViz.updateRange(minValue.value, maxValue.value)
    render()
  }
}

/**
 * 计算压力统计数据
 */
function calculatePressureStats() {
  if (!pressureViz || !pressureViz.mesh.geometry) return

  const geometry = pressureViz.mesh.geometry
  const pressureAttribute = geometry.attributes.pressure

  if (!pressureAttribute) return

  let min = Infinity
  let max = -Infinity
  let sum = 0
  const count = pressureAttribute.count

  for (let i = 0; i < count; i++) {
    const value = pressureAttribute.getX(i)
    min = Math.min(min, value)
    max = Math.max(max, value)
    sum += value
  }

  setPressureStats({ min, max, avg: sum / count })
}

/**
 * 设置鼠标交互
 */
function setupMouseInteraction() {
  if (!renderer || !camera || !scene) return

  const raycaster = new THREE.Raycaster()
  const mouse = new THREE.Vector2()

  const onMouseMove = (event: MouseEvent) => {
    if (!container.value || !pressureViz) return

    const rect = container.value.getBoundingClientRect()
    mouse.x = ((event.clientX - rect.left) / rect.width) * 2 - 1
    mouse.y = -((event.clientY - rect.top) / rect.height) * 2 + 1

    raycaster.setFromCamera(mouse, camera!)
    const intersects = raycaster.intersectObject(pressureViz.mesh)

    if (intersects.length > 0) {
      const intersection = intersects[0]
      if (!intersection) {
        setSelectedPressure(null)
        return
      }
      
      const geometry = pressureViz.mesh.geometry

      if (geometry && geometry.attributes.pressure && intersection.face) {
        const face = intersection.face
        const pressureAttribute = geometry.attributes.pressure
        const pressure1 = pressureAttribute.getX(face.a)
        const pressure2 = pressureAttribute.getX(face.b)
        const pressure3 = pressureAttribute.getX(face.c)
        const avgPressure = (pressure1 + pressure2 + pressure3) / 3

        setSelectedPressure(avgPressure)
      }
    } else {
      setSelectedPressure(null)
    }
  }

  renderer.domElement.addEventListener('mousemove', onMouseMove)
}

/**
 * 重置视图
 */
function reset() {
  if (camera && controls) {
    camera.position.set(0, 0, 10)
    controls.target.set(0, 0, 0)
    controls.update()
    render()
  }
}

/**
 * 清理资源
 */
function dispose() {
  if (animationId) cancelAnimationFrame(animationId)
  window.removeEventListener('resize', onWindowResize)

  if (pressureViz) {
    pressureViz.dispose()
    pressureViz = null
  }

  if (controls) {
    controls.dispose()
    controls = null
  }

  if (renderer) {
    renderer.dispose()
    renderer = null
  }

  if (scene) {
    scene.traverse((object) => {
      if (object instanceof THREE.Mesh) {
        if (object.geometry) object.geometry.dispose()
        if (object.material) {
          if (Array.isArray(object.material)) {
            object.material.forEach(m => m.dispose())
          } else {
            object.material.dispose()
          }
        }
      }
    })
    scene = null
  }

  camera = null
}

// 暴露方法
defineExpose({ reset })

// 生命周期
onMounted(init)
onBeforeUnmount(dispose)
</script>

<style scoped>
.pressure-viewer {
  position: relative;
  width: 100%;
  height: 100vh;
  overflow: hidden;
}

.viewer-container {
  width: 100%;
  height: 100%;
  position: absolute;
  top: 0;
  left: 0;
}
</style>

// src/components/PressureViewer/index.tsx
import React, { useEffect, useRef, useState, useImperativeHandle, forwardRef } from 'react';
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { createPressureVisualization, type PressureVisualization } from '../../utils/pressureData';
import { usePressureVisualization } from '../../composables';
import type { Model } from '../../core/types';
import './PressureViewer.style.css';

export interface PressureViewerProps {
  model: Model;
  onLoading?: (progress: number) => void;
  onLoaded?: () => void;
  onError?: (error: unknown) => void;
}

export interface PressureViewerRef {
  reset: () => void;
}

const PressureViewer = forwardRef<PressureViewerRef, PressureViewerProps>(({ model, onLoading, onLoaded, onError }, ref) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const [isLoading, setIsLoading] = useState(true);

  const {
    colorMap,
    minValue,
    maxValue,
    selectedPressure,
    pressureStats,
    pressureLabels,
    colorBarGradient,
    getColorForPressure,
    formatPressureValue,
    setPressureStats,
    setSelectedPressure
  } = usePressureVisualization();

  const threeInstance = useRef<{
    scene: THREE.Scene;
    camera: THREE.PerspectiveCamera;
    renderer: THREE.WebGLRenderer;
    controls: OrbitControls;
    pressureViz: PressureVisualization;
    animationId: number;
  } | null>(null);

  useImperativeHandle(ref, () => ({
    reset: () => {
      const inst = threeInstance.current;
      if (inst) {
        inst.camera.position.set(0, 0, 10);
        inst.controls.target.set(0, 0, 0);
        inst.controls.update();
        inst.renderer.render(inst.scene, inst.camera);
      }
    }
  }));

  useEffect(() => {
    if (!containerRef.current || !model) return;

    let isDisposed = false;
    let animationId: number;

    const scene = new THREE.Scene();
    scene.background = new THREE.Color(0xffffff);

    const width = containerRef.current.clientWidth;
    const height = containerRef.current.clientHeight;
    const camera = new THREE.PerspectiveCamera(60, width / height, 1, 100);
    camera.position.set(0, 0, 10);

    const renderer = new THREE.WebGLRenderer({ antialias: true });
    renderer.setPixelRatio(window.devicePixelRatio);
    renderer.setSize(width, height);
    containerRef.current.appendChild(renderer.domElement);

    const controls = new OrbitControls(camera, renderer.domElement);
    const render = () => {
      renderer.render(scene, camera);
    };
    controls.addEventListener('change', render);

    const pointLight = new THREE.PointLight(0xffffff, 3, 0, 0);
    camera.add(pointLight);
    scene.add(camera);

    createPressureVisualization(
      scene,
      model.file,
      { colorMap, minValue, maxValue },
      {
        loading: (p) => {
          if (!isDisposed) onLoading?.(p);
        },
        loaded: () => {
          if (!isDisposed) {
            setIsLoading(false);
            onLoaded?.();
          }
        },
        error: (e) => {
          if (!isDisposed) {
            setIsLoading(false);
            onError?.(e);
          }
        }
      }
    ).then((viz) => {
      if (isDisposed) {
        viz.dispose();
        return;
      }

      scene.add(viz.legend);

      // calculate stats
      if (viz.mesh.geometry?.attributes.pressure) {
        const attr = viz.mesh.geometry.attributes.pressure;
        let min = Infinity, max = -Infinity, sum = 0;
        for (let i = 0; i < attr.count; i++) {
          const v = attr.getX(i);
          min = Math.min(min, v);
          max = Math.max(max, v);
          sum += v;
        }
        setPressureStats({ min, max, avg: sum / attr.count });
      }

      const animate = () => {
        animationId = requestAnimationFrame(animate);
        controls.update();
        render();
      };
      animate();

      const raycaster = new THREE.Raycaster();
      const mouse = new THREE.Vector2();

      const onMouseMove = (e: MouseEvent) => {
        if (!containerRef.current) return;
        const rect = containerRef.current.getBoundingClientRect();
        mouse.x = ((e.clientX - rect.left) / rect.width) * 2 - 1;
        mouse.y = -((e.clientY - rect.top) / rect.height) * 2 + 1;

        raycaster.setFromCamera(mouse, camera);
        const intersects = raycaster.intersectObject(viz.mesh);

        if (intersects.length > 0 && intersects[0].face) {
          const face = intersects[0].face;
          const attr = viz.mesh.geometry.attributes.pressure;
          if (attr) {
            const p1 = attr.getX(face.a);
            const p2 = attr.getX(face.b);
            const p3 = attr.getX(face.c);
            setSelectedPressure((p1 + p2 + p3) / 3);
          }
        } else {
          setSelectedPressure(null);
        }
      };

      renderer.domElement.addEventListener('mousemove', onMouseMove);

      threeInstance.current = {
        scene, camera, renderer, controls, pressureViz: viz, animationId
      };
    }).catch(e => {
      if (!isDisposed) {
        console.error(e);
        setIsLoading(false);
        onError?.(e);
      }
    });

    const onResize = () => {
      if (!containerRef.current) return;
      const w = containerRef.current.clientWidth;
      const h = containerRef.current.clientHeight;
      camera.aspect = w / h;
      camera.updateProjectionMatrix();
      renderer.setSize(w, h);
      render();
    };
    window.addEventListener('resize', onResize);

    return () => {
      isDisposed = true;
      window.removeEventListener('resize', onResize);
      if (animationId) cancelAnimationFrame(animationId);

      if (threeInstance.current) {
        const inst = threeInstance.current;
        inst.pressureViz.dispose();
        inst.controls.dispose();
        inst.renderer.dispose();
        if (containerRef.current?.contains(inst.renderer.domElement)) {
          containerRef.current.removeChild(inst.renderer.domElement);
        }
      }
    };
  }, [model]);

  // Handle colorMap and range updates using separate effect
  useEffect(() => {
    if (threeInstance.current?.pressureViz) {
      const viz = threeInstance.current.pressureViz;
      viz.updateColorMap(colorMap);
      viz.updateRange(minValue, maxValue);
      threeInstance.current.renderer.render(threeInstance.current.scene, threeInstance.current.camera);
    }
  }, [colorMap, minValue, maxValue]);

  return (
    <div className="pressure-viewer">
      <div ref={containerRef} className="viewer-container" />
      
      {!isLoading && (
        <>
          <div className="pressure-control-panel">
            {/* Control Panel Simplified */}
            <h3>压力可视化控制</h3>
            <div className="stats">
              <div>最小值: {formatPressureValue(pressureStats.min)}</div>
              <div>最大值: {formatPressureValue(pressureStats.max)}</div>
              <div>平均值: {formatPressureValue(pressureStats.avg)}</div>
            </div>
            {/* Legend Simplified */}
            <div className="pressure-legend">
              <div className="color-bar" style={{ background: colorBarGradient }} />
              <div className="labels">
                {pressureLabels.map((l: any) => <span key={l.value}>{l.label}</span>)}
              </div>
              {selectedPressure !== null && (
                <div className="selected-value">
                  当前: {formatPressureValue(selectedPressure)}
                </div>
              )}
            </div>
          </div>
        </>
      )}
    </div>
  );
});

PressureViewer.displayName = 'PressureViewer';
export default PressureViewer;
